function exportGUI   
    %% initialize variables

    % export parameters   
    exportGroup = 'Amplitude';
    numEvents = 200;
    freqChoice = 'From first N events';
    eventsChoice = 'Exactly N events';
    riseStartValue = 10;            % start of average trace rise measurement
    riseEndValue = 90;              % end of average trace rise measurement
    decayStartValue = 80;           % start of average trace rise measurement
    decayEndValue = 20;             % end of average trace rise measurement
    nameMatch = '';
   
    %% initialize export GUI
    
    % create and position main panel
    mainPanel = uifigure;
    mainPanelWidth = mainPanel.Position(3);
    mainPanelHeight = mainPanel.Position(4);
      
    % radio button group for export group selection
    exportGroupHeight = 0.2*mainPanelHeight;
    exportGroupWidth = 0.2*mainPanelWidth;
    exportGroupCheck = uibuttongroup('Parent',mainPanel,...
        'Title','Group to Export',...
        'SelectionChangedFcn',@exportGroupChange,...
        'Position',[mainPanelWidth*0.15-(exportGroupWidth/2) mainPanelHeight*0.675 exportGroupWidth exportGroupHeight]);
    uiradiobutton('Parent',exportGroupCheck,...
        'Text','Full event',...
        'Position',[10 0.55*exportGroupHeight 100 15]);
    uiradiobutton('Parent',exportGroupCheck,...
        'Text','Amplitude',...
        'Position',[10 0.3*exportGroupHeight 100 15],...
        'Value',true);
    uiradiobutton('Parent',exportGroupCheck,...
        'Text','Frequency',...
        'Position',[10 0.05*exportGroupHeight 100 15]);
    
    % labels and fields defining event number limits
    numEeventsHeight = 0.2*mainPanelHeight;
    numEventsWidth = 0.25*mainPanelWidth;
    numEventsCheck = uibuttongroup('Parent',mainPanel,...
        'Title','Event # Limits',...
        'SelectionChangedFcn',@eventsChange,...
        'Position',[mainPanelWidth*0.45-(numEventsWidth/2) mainPanelHeight*0.675 numEventsWidth numEeventsHeight]);
    uiradiobutton('Parent',numEventsCheck,...
        'Text','Exactly N events',...
        'Position',[10 0.425*numEeventsHeight 150 15]);
    uiradiobutton('Parent',numEventsCheck,...
        'Text','Up to N events',...
        'Position',[10 0.1*numEeventsHeight 150 15]);
    
    % radio button group for frequency calculation preference
    freqpPrefHeight = 0.2*mainPanelHeight;
    freqPrefWidth = 0.3*mainPanelWidth;
    freqPrefCheck = uibuttongroup('Parent',mainPanel,...
        'Title','Frequency Calculation',...
        'SelectionChangedFcn',@freqPrefChange,...
        'Position',[mainPanelWidth*0.8-(freqPrefWidth/2) mainPanelHeight*0.675 freqPrefWidth freqpPrefHeight]);
    uiradiobutton('Parent',freqPrefCheck,...
        'Text','From first N events',...
        'Position',[10 0.425*freqpPrefHeight 150 15]);
    uiradiobutton('Parent',freqPrefCheck,...
        'Text','From all events',...
        'Position',[10 0.1*freqpPrefHeight 150 15]);
    
    % labels and fields relating to the number of events to export
    uilabel('Parent',mainPanel,...
        'Text','Number of Events (N)',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.20-(150/2) mainPanelHeight*0.55 150 20]);
    exportNumField = uieditfield(mainPanel,...
        'numeric',...
        'Value',numEvents,...
        'ValueChangedFcn',@numEventsUpdate,...
        'Position',[mainPanelWidth*0.35-(30/2) mainPanelHeight*0.55 30 20],...
        'HorizontalAlignment','Center');
    
    % string field for file name match
    uilabel('Parent',mainPanel,...
        'Text','Export file names that include',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.62-(175/2) mainPanelHeight*0.55 175 20]);
    nameMatchField = uieditfield(mainPanel,...
        'text',...
        'Value','',...
        'ValueChangedFcn',@nameMatchUpdate,...
        'Position',[mainPanelWidth*0.85-(75/2) mainPanelHeight*0.55 75 20],...
        'HorizontalAlignment','Center');
    
    % average trace rise measurement preferences
    uilabel('Parent',mainPanel,...
        'Text','Average Trace',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.333-(200/2) mainPanelHeight*0.42 200 20]);
    uilabel('Parent',mainPanel,...
        'Text','Rise Measurement',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.333-(200/2) mainPanelHeight*0.38 200 20]);
    riseStartField = uieditfield(mainPanel,...
        'numeric',...
        'Value',riseStartValue,...
        'ValueChangedFcn',@averageTraceMeasurementUpdate,...
        'Position',[mainPanelWidth*0.376-(30/2) mainPanelHeight*0.32 30 20],...
        'HorizontalAlignment','Center');
    uilabel('Parent',mainPanel,...
        'Text','Begin %',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.296-(50/2) mainPanelHeight*0.32 60 20]);
    riseEndField = uieditfield(mainPanel,...
        'numeric',...
        'Value',riseEndValue,...
        'ValueChangedFcn',@averageTraceMeasurementUpdate,...
        'Position',[mainPanelWidth*0.376-(30/2) mainPanelHeight*0.26 30 20],...
        'HorizontalAlignment','Center');
    uilabel('Parent',mainPanel,...
        'Text','End %',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.296-(50/2) mainPanelHeight*0.26 50 20]);
    
    % average trace decay measurement preferences
    uilabel('Parent',mainPanel,...
        'Text','Average Trace',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.667-(225/2) mainPanelHeight*0.42 225 20]);
    uilabel('Parent',mainPanel,...
        'Text','Decay Measurement',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.667-(225/2) mainPanelHeight*0.38 225 20]);
    decayStartField = uieditfield(mainPanel,...
        'numeric',...
        'Value',decayStartValue,...
        'ValueChangedFcn',@averageTraceMeasurementUpdate,...
        'Position',[mainPanelWidth*0.71-(30/2) mainPanelHeight*0.32 30 20],...
        'HorizontalAlignment','Center');
    uilabel('Parent',mainPanel,...
        'Text','Begin %',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.63-(50/2) mainPanelHeight*0.32 60 20]);
    decayEndField = uieditfield(mainPanel,...
        'numeric',...
        'Value',decayEndValue,...
        'ValueChangedFcn',@averageTraceMeasurementUpdate,...
        'Position',[mainPanelWidth*0.71-(30/2) mainPanelHeight*0.26 30 20],...
        'HorizontalAlignment','Center');
    uilabel('Parent',mainPanel,...
        'Text','End %',...
        'fontweight', 'bold',...
        'HorizontalAlignment','Center',...
        'Position',[mainPanelWidth*0.63-(50/2) mainPanelHeight*0.26 50 20]);
    
    uibutton('Parent',mainPanel,...
        'Text',sprintf('%s\n%s','Begin','Export'),...
        'ButtonPushedFcn',@beginButton,...
        'fontweight', 'bold',...
        'Position',[mainPanelWidth*0.2-(100/2) mainPanelHeight*0.1 100 40]);
    
    uibutton('Parent',mainPanel,...
        'Text','Exit',...
        'ButtonPushedFcn',@exitButton,...
        'fontweight', 'bold',...
        'Position',[mainPanelWidth*0.8-(100/2) mainPanelHeight*0.1 100 40]); 
    
    %% wait for user input    
    uiwait(mainPanel);
    
    %% export functions
    
    function beginButton(~,~)
        switch exportGroup
            case 'Amplitude'
                exportGroup = 'amplitude';
            case 'Full Event'
                exportGroup = 'full';
        end
        
        switch freqChoice
            case 'From first N events'
                freqChoice = 'limited';
            case 'From all events'
                freqChoice = 'all';
        end
        
        switch eventsChoice
            case 'Exactly N events'
                eventsChoice = 'exactly';
            case 'Up to N events'
                eventsChoice = 'all';
        end
        
        args = {...
            'exportedGroup',exportGroup,...
            'frequencyCalculation',freqChoice,...
            'numberOfEvents',numEvents,...
            'eventLimit',eventsChoice,...
            'riseLimits',[riseStartValue riseEndValue],...
            'decayLimits',[decayStartValue decayEndValue],...
            'match',nameMatch};
        
        [OrganizedData, RawDataMatrix_AllCells, RawDataTable_AllCells, AverageTrace_AllCells]...
            = exportFromFile(args{:});

        
        % export variables to workspace
        assignin('base','AverageTrace_AllCells',AverageTrace_AllCells);
        assignin('base','OrganizedData',OrganizedData);
        assignin('base','RawDataMatrix_AllCells',RawDataMatrix_AllCells);
        assignin('base','RawDataTable_AllCells',RawDataTable_AllCells);        
        
        message = 'Export completed.';
        uialert(mainPanel,message,'','Icon','success');
    end
    
    function exitButton(~,~)
    % exit the GUI
        delete(mainPanel);
    end

    function exportGroupChange(~,event)
    % changes which group is auto-exported
        exportGroup = event.NewValue.Text;
    end

    function freqPrefChange(~,event)
    % changes how frequency is calculated during export
        freqChoice = event.NewValue.Text;
    end

    function eventsChange(~,event)
    % changes the limits on event numbers
        eventsChoice = event.NewValue.Text;
    end

    function numEventsUpdate(~,~)
    % changes how many events are exported
        numEvents = exportNumField.Value;
    end

    function nameMatchUpdate(~,~)
    % string to match in file names
        nameMatch = nameMatchField.Value;
    end


    function averageTraceMeasurementUpdate(~,~)
    % changes the start and end values for average trace kinetics
    % measurements
        riseStartValue = riseStartField.Value;
        riseEndValue = riseEndField.Value;
        decayStartValue = decayStartField.Value;
        decayEndValue = decayEndField.Value;
    end
end